import React, { useContext, useEffect, useState } from "react";
import { AuthContext } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";
import api from "../utils/axios";

const emptyForm = { title: "", description: "", category: "", location: "", date: "", time: "", price: 0, totalSeats: 50, availableSeats: 50, image: "" };

const AdminDashboard = () => {
  const { user } = useContext(AuthContext); const navigate = useNavigate();
  const [events, setEvents] = useState([]); const [bookings, setBookings] = useState([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); const [e, b] = await Promise.all([api.get("/events"), api.get("/bookings")]); setEvents(e.data.data || []); setBookings(b.data.data || []); } catch (err) { setError(err.response?.data?.message || "Unable to load admin data."); } finally { setLoading(false); } };
  useEffect(() => { if (!user) navigate("/login"); else if (user.role !== "admin") navigate("/"); else load(); }, [user, navigate]);
  const submit = async (e) => { e.preventDefault(); setError(""); setMessage(""); try { const payload = { ...form, price: Number(form.price), totalSeats: Number(form.totalSeats), availableSeats: Number(form.availableSeats) }; if (editing) await api.put(`/events/${editing}`, payload); else await api.post("/events", payload); setForm(emptyForm); setEditing(null); setMessage(editing ? "Event updated." : "Event created."); load(); } catch (err) { setError(err.response?.data?.message || "Unable to save event."); } };
  const remove = async (id) => { if (!window.confirm("Delete this event?")) return; try { await api.delete(`/events/${id}`); load(); } catch (err) { alert(err.response?.data?.message || "Unable to delete event"); } };
  const confirm = async (id, paymentStatus) => { try { await api.put(`/bookings/${id}/confirm`, { paymentStatus }); load(); } catch (err) { alert(err.response?.data?.message || "Unable to update booking"); } };
  if (loading) return <div className="py-20 text-center text-gray-500">Loading admin dashboard...</div>;
  return <div className="max-w-7xl mx-auto space-y-10"><div><p className="text-sm uppercase tracking-widest text-gray-500">Admin</p><h1 className="text-4xl font-black">Eventora Control Center</h1><p className="text-gray-500 mt-2">Manage events, bookings and payment confirmation.</p></div>
    {message && <div className="bg-green-50 text-green-700 p-4 rounded-xl">{message}</div>}{error && <div className="bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}
    <section className="bg-white border border-gray-100 rounded-2xl p-6 shadow-sm"><div className="flex justify-between items-center mb-6"><h2 className="text-2xl font-bold">{editing ? "Edit Event" : "Create Event"}</h2>{editing && <button onClick={() => { setEditing(null); setForm(emptyForm); }} className="text-sm underline">Cancel edit</button>}</div><form onSubmit={submit} className="grid md:grid-cols-2 gap-4">{[["title","Title"],["category","Category"],["location","Location"],["date","Date"],["time","Time"],["image","Image URL"]].map(([key,label]) => <div key={key}><label className="block text-sm font-semibold mb-1">{label}</label><input required={!["image"].includes(key)} type={key === "date" ? "date" : key === "time" ? "time" : "text"} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="w-full px-3 py-2.5 border rounded-lg" /></div>)}<div><label className="block text-sm font-semibold mb-1">Price</label><input type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} className="w-full px-3 py-2.5 border rounded-lg" /></div><div><label className="block text-sm font-semibold mb-1">Total Seats</label><input type="number" min="1" value={form.totalSeats} onChange={(e) => setForm({ ...form, totalSeats: e.target.value, availableSeats: editing ? form.availableSeats : e.target.value })} className="w-full px-3 py-2.5 border rounded-lg" /></div><div className="md:col-span-2"><label className="block text-sm font-semibold mb-1">Description</label><textarea required rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="w-full px-3 py-2.5 border rounded-lg" /></div><div><label className="block text-sm font-semibold mb-1">Available Seats</label><input type="number" min="0" value={form.availableSeats} onChange={(e) => setForm({ ...form, availableSeats: e.target.value })} className="w-full px-3 py-2.5 border rounded-lg" /></div><div className="flex items-end"><button className="w-full bg-gray-900 text-white py-3 rounded-lg font-bold">{editing ? "Update Event" : "Create Event"}</button></div></form></section>
    <section><h2 className="text-2xl font-bold mb-5">Events ({events.length})</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{events.map((event) => <article key={event._id} className="bg-white border rounded-2xl p-5"><h3 className="font-bold text-lg">{event.title}</h3><p className="text-sm text-gray-500 mt-2">{event.location} · {new Date(event.date).toLocaleDateString()}</p><p className="text-sm mt-2">Seats: {event.availableSeats}/{event.totalSeats}</p><div className="flex gap-3 mt-5"><button onClick={() => { setEditing(event._id); setForm({ ...event, date: new Date(event.date).toISOString().slice(0,10) }); window.scrollTo({top:0,behavior:"smooth"}); }} className="px-3 py-2 rounded-lg bg-gray-100 font-semibold">Edit</button><button onClick={() => remove(event._id)} className="px-3 py-2 rounded-lg bg-red-50 text-red-600 font-semibold">Delete</button></div></article>)}</div></section>
    <section><h2 className="text-2xl font-bold mb-5">Bookings ({bookings.length})</h2><div className="overflow-x-auto bg-white border rounded-2xl"><table className="min-w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-4 text-left">Event</th><th className="p-4 text-left">User</th><th className="p-4 text-left">Tickets</th><th className="p-4 text-left">Amount</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">Action</th></tr></thead><tbody>{bookings.map((b) => <tr key={b._id} className="border-t"><td className="p-4">{b.eventId?.title || "Deleted event"}</td><td className="p-4">{b.userId?.email || "—"}</td><td className="p-4">{b.numberOfTickets}</td><td className="p-4">₹{b.amount}</td><td className="p-4">{b.status} / {b.paymentStatus}</td><td className="p-4">{b.status !== "cancelled" && b.status !== "confirmed" && <button onClick={() => confirm(b._id, "Paid")} className="px-3 py-2 bg-gray-900 text-white rounded-lg">Confirm Paid</button>}</td></tr>)}</tbody></table></div></section>
  </div>;
};
export default AdminDashboard;
